import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import MainLayout from "@/components/layouts/MainLayout";
import "./globals.css";
import ThemeProvider from "@/context/ThemeProvider";

const inter = Poppins({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Ecommerce | Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex`}>
        <ThemeProvider attribute="class" defaultTheme="dark">
          <MainLayout>{children}</MainLayout>
        </ThemeProvider>
      </body>
    </html>
  );
}
